/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTC2 (number 45), J24[8]
  @{ */
#define BOARD_LED_BLUE_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_LED_BLUE_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_LED_BLUE_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTC3 (number 46), J1[14]
  @{ */
#define BOARD_DEBUG_UART_RX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_DEBUG_UART_RX_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                       /* @} */

/*! @name PORTC4 (number 49), J8[P2]/J24[9]/uSD_card_CS
  @{ */
#define BOARD_DEBUG_UART_TX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_DEBUG_UART_TX_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORTA12 (number 28), J1[5]/I2S0_TXD0
  @{ */
#define MOTOR_A_PIN_FORWARD_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define MOTOR_A_PIN_FORWARD_PORT PORTA /*!<@brief PORT device name: PORTA */
#define MOTOR_A_PIN_FORWARD_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                       /* @} */

/*! @name PORTB0 (number 35), J24[2]/LLWU_P5
  @{ */
#define MOTOR_A_PIN_REVERSE_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define MOTOR_A_PIN_REVERSE_PORT PORTB /*!<@brief PORT device name: PORTB */
#define MOTOR_A_PIN_REVERSE_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Motor_A_InitPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTA1 (number 23), J2[4]/RED_LED
  @{ */
#define PI_LEDRGB_RED_PORT PORTA /*!<@brief PORT device name: PORTA */
#define PI_LEDRGB_RED_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                 /* @} */

/*! @name PORTA2 (number 24), J1[8]/GREEN_LED
  @{ */
#define PI_LEDRGB_GREEN_PORT PORTA /*!<@brief PORT device name: PORTA */
#define PI_LEDRGB_GREEN_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Pi_Init_UARTPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
