# Topics
ACCELERATION_TOPIC = b'acceleration'
ACKNOWLEDGE_TOPIC = b'acknowledge'
ACOUSTIC_TOPIC = b'acoustic'
CRANE_CMD_TOPIC = b'cranecommand'
CURRENT_TOPIC = b'current'
DIRECTION_TOPIC = b'direction'
DISTANCE_TOPIC = b'acceleration'
HEARTBEAT_TOPIC = b'heartbeat'
MOVE_CMD_TOPIC = b'movecommand'
NUMBER_DETECTOR_TOPIC = b'numberdetector'
SPEED_TOPIC = b'speed'
SYSTEM_CMD_TOPIC = b'systemcommand'
SYSTEM_STATUS_TOPIC = b'systemstatus'
