// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: numberReco.proto

#include "numberReco.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace plateReco {
class plateRecoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<plateReco> _instance;
} _plateReco_default_instance_;
}  // namespace plateReco
static void InitDefaultsplateReco_numberReco_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::plateReco::_plateReco_default_instance_;
    new (ptr) ::plateReco::plateReco();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::plateReco::plateReco::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_plateReco_numberReco_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsplateReco_numberReco_2eproto}, {}};

void InitDefaults_numberReco_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_plateReco_numberReco_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_numberReco_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_numberReco_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_numberReco_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_numberReco_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::plateReco::plateReco, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::plateReco::plateReco, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::plateReco::plateReco, message_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::plateReco::plateReco)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::plateReco::_plateReco_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_numberReco_2eproto = {
  {}, AddDescriptors_numberReco_2eproto, "numberReco.proto", schemas,
  file_default_instances, TableStruct_numberReco_2eproto::offsets,
  file_level_metadata_numberReco_2eproto, 1, file_level_enum_descriptors_numberReco_2eproto, file_level_service_descriptors_numberReco_2eproto,
};

const char descriptor_table_protodef_numberReco_2eproto[] =
  "\n\020numberReco.proto\022\tplateReco\"\034\n\tplateRe"
  "co\022\017\n\007message\030\001 \002(\t"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_numberReco_2eproto = {
  false, InitDefaults_numberReco_2eproto, 
  descriptor_table_protodef_numberReco_2eproto,
  "numberReco.proto", &assign_descriptors_table_numberReco_2eproto, 59,
};

void AddDescriptors_numberReco_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_numberReco_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_numberReco_2eproto = []() { AddDescriptors_numberReco_2eproto(); return true; }();
namespace plateReco {

// ===================================================================

void plateReco::InitAsDefaultInstance() {
}
class plateReco::HasBitSetters {
 public:
  static void set_has_message(plateReco* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int plateReco::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

plateReco::plateReco()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:plateReco.plateReco)
}
plateReco::plateReco(const plateReco& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_message()) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  // @@protoc_insertion_point(copy_constructor:plateReco.plateReco)
}

void plateReco::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_plateReco_numberReco_2eproto.base);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

plateReco::~plateReco() {
  // @@protoc_insertion_point(destructor:plateReco.plateReco)
  SharedDtor();
}

void plateReco::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void plateReco::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const plateReco& plateReco::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_plateReco_numberReco_2eproto.base);
  return *internal_default_instance();
}


void plateReco::Clear() {
// @@protoc_insertion_point(message_clear_start:plateReco.plateReco)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    message_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* plateReco::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<plateReco*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // required string message = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("plateReco.plateReco.message");
        object = msg->mutable_message();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool plateReco::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:plateReco.plateReco)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string message = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "plateReco.plateReco.message");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:plateReco.plateReco)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:plateReco.plateReco)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void plateReco::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:plateReco.plateReco)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string message = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "plateReco.plateReco.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:plateReco.plateReco)
}

::google::protobuf::uint8* plateReco::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:plateReco.plateReco)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string message = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "plateReco.plateReco.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:plateReco.plateReco)
  return target;
}

size_t plateReco::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:plateReco.plateReco)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required string message = 1;
  if (has_message()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void plateReco::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:plateReco.plateReco)
  GOOGLE_DCHECK_NE(&from, this);
  const plateReco* source =
      ::google::protobuf::DynamicCastToGenerated<plateReco>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:plateReco.plateReco)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:plateReco.plateReco)
    MergeFrom(*source);
  }
}

void plateReco::MergeFrom(const plateReco& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:plateReco.plateReco)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_message()) {
    _has_bits_[0] |= 0x00000001u;
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
}

void plateReco::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:plateReco.plateReco)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void plateReco::CopyFrom(const plateReco& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:plateReco.plateReco)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool plateReco::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void plateReco::Swap(plateReco* other) {
  if (other == this) return;
  InternalSwap(other);
}
void plateReco::InternalSwap(plateReco* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata plateReco::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_numberReco_2eproto);
  return ::file_level_metadata_numberReco_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace plateReco
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::plateReco::plateReco* Arena::CreateMaybeMessage< ::plateReco::plateReco >(Arena* arena) {
  return Arena::CreateInternal< ::plateReco::plateReco >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
