# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acknowledge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='acknowledge.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x61\x63knowledge.proto\"0\n\x0b\x41\x63knowledge\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x11\n\tcomponent\x18\x02 \x01(\tb\x06proto3')
)




_ACKNOWLEDGE = _descriptor.Descriptor(
  name='Acknowledge',
  full_name='Acknowledge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='Acknowledge.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='component', full_name='Acknowledge.component', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['Acknowledge'] = _ACKNOWLEDGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Acknowledge = _reflection.GeneratedProtocolMessageType('Acknowledge', (_message.Message,), dict(
  DESCRIPTOR = _ACKNOWLEDGE,
  __module__ = 'acknowledge_pb2'
  # @@protoc_insertion_point(class_scope:Acknowledge)
  ))
_sym_db.RegisterMessage(Acknowledge)


# @@protoc_insertion_point(module_scope)
