// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acknowledge.proto

public final class AcknowledgeOuterClass {
  private AcknowledgeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AcknowledgeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Acknowledge)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *e.g received_number, received_direction, received_acoustic_command, received_move_command,
     * </pre>
     *
     * <code>string action = 1;</code>
     */
    java.lang.String getAction();
    /**
     * <pre>
     *e.g received_number, received_direction, received_acoustic_command, received_move_command,
     * </pre>
     *
     * <code>string action = 1;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <pre>
     *e.g linedetection, numberdetection, movement, acoustic, controlflow, webapp
     * </pre>
     *
     * <code>string component = 2;</code>
     */
    java.lang.String getComponent();
    /**
     * <pre>
     *e.g linedetection, numberdetection, movement, acoustic, controlflow, webapp
     * </pre>
     *
     * <code>string component = 2;</code>
     */
    com.google.protobuf.ByteString
        getComponentBytes();
  }
  /**
   * Protobuf type {@code Acknowledge}
   */
  public  static final class Acknowledge extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Acknowledge)
      AcknowledgeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Acknowledge.newBuilder() to construct.
    private Acknowledge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Acknowledge() {
      action_ = "";
      component_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Acknowledge(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              component_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AcknowledgeOuterClass.internal_static_Acknowledge_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AcknowledgeOuterClass.internal_static_Acknowledge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AcknowledgeOuterClass.Acknowledge.class, AcknowledgeOuterClass.Acknowledge.Builder.class);
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object action_;
    /**
     * <pre>
     *e.g received_number, received_direction, received_acoustic_command, received_move_command,
     * </pre>
     *
     * <code>string action = 1;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *e.g received_number, received_direction, received_acoustic_command, received_move_command,
     * </pre>
     *
     * <code>string action = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPONENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object component_;
    /**
     * <pre>
     *e.g linedetection, numberdetection, movement, acoustic, controlflow, webapp
     * </pre>
     *
     * <code>string component = 2;</code>
     */
    public java.lang.String getComponent() {
      java.lang.Object ref = component_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        component_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *e.g linedetection, numberdetection, movement, acoustic, controlflow, webapp
     * </pre>
     *
     * <code>string component = 2;</code>
     */
    public com.google.protobuf.ByteString
        getComponentBytes() {
      java.lang.Object ref = component_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        component_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, action_);
      }
      if (!getComponentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, component_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, action_);
      }
      if (!getComponentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, component_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AcknowledgeOuterClass.Acknowledge)) {
        return super.equals(obj);
      }
      AcknowledgeOuterClass.Acknowledge other = (AcknowledgeOuterClass.Acknowledge) obj;

      boolean result = true;
      result = result && getAction()
          .equals(other.getAction());
      result = result && getComponent()
          .equals(other.getComponent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + COMPONENT_FIELD_NUMBER;
      hash = (53 * hash) + getComponent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AcknowledgeOuterClass.Acknowledge parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AcknowledgeOuterClass.Acknowledge parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AcknowledgeOuterClass.Acknowledge parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AcknowledgeOuterClass.Acknowledge parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AcknowledgeOuterClass.Acknowledge parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AcknowledgeOuterClass.Acknowledge parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AcknowledgeOuterClass.Acknowledge parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AcknowledgeOuterClass.Acknowledge parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AcknowledgeOuterClass.Acknowledge parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AcknowledgeOuterClass.Acknowledge parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AcknowledgeOuterClass.Acknowledge parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AcknowledgeOuterClass.Acknowledge parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AcknowledgeOuterClass.Acknowledge prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Acknowledge}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Acknowledge)
        AcknowledgeOuterClass.AcknowledgeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AcknowledgeOuterClass.internal_static_Acknowledge_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AcknowledgeOuterClass.internal_static_Acknowledge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AcknowledgeOuterClass.Acknowledge.class, AcknowledgeOuterClass.Acknowledge.Builder.class);
      }

      // Construct using AcknowledgeOuterClass.Acknowledge.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        action_ = "";

        component_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AcknowledgeOuterClass.internal_static_Acknowledge_descriptor;
      }

      @java.lang.Override
      public AcknowledgeOuterClass.Acknowledge getDefaultInstanceForType() {
        return AcknowledgeOuterClass.Acknowledge.getDefaultInstance();
      }

      @java.lang.Override
      public AcknowledgeOuterClass.Acknowledge build() {
        AcknowledgeOuterClass.Acknowledge result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AcknowledgeOuterClass.Acknowledge buildPartial() {
        AcknowledgeOuterClass.Acknowledge result = new AcknowledgeOuterClass.Acknowledge(this);
        result.action_ = action_;
        result.component_ = component_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AcknowledgeOuterClass.Acknowledge) {
          return mergeFrom((AcknowledgeOuterClass.Acknowledge)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AcknowledgeOuterClass.Acknowledge other) {
        if (other == AcknowledgeOuterClass.Acknowledge.getDefaultInstance()) return this;
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getComponent().isEmpty()) {
          component_ = other.component_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AcknowledgeOuterClass.Acknowledge parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AcknowledgeOuterClass.Acknowledge) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <pre>
       *e.g received_number, received_direction, received_acoustic_command, received_move_command,
       * </pre>
       *
       * <code>string action = 1;</code>
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *e.g received_number, received_direction, received_acoustic_command, received_move_command,
       * </pre>
       *
       * <code>string action = 1;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *e.g received_number, received_direction, received_acoustic_command, received_move_command,
       * </pre>
       *
       * <code>string action = 1;</code>
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *e.g received_number, received_direction, received_acoustic_command, received_move_command,
       * </pre>
       *
       * <code>string action = 1;</code>
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *e.g received_number, received_direction, received_acoustic_command, received_move_command,
       * </pre>
       *
       * <code>string action = 1;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object component_ = "";
      /**
       * <pre>
       *e.g linedetection, numberdetection, movement, acoustic, controlflow, webapp
       * </pre>
       *
       * <code>string component = 2;</code>
       */
      public java.lang.String getComponent() {
        java.lang.Object ref = component_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          component_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *e.g linedetection, numberdetection, movement, acoustic, controlflow, webapp
       * </pre>
       *
       * <code>string component = 2;</code>
       */
      public com.google.protobuf.ByteString
          getComponentBytes() {
        java.lang.Object ref = component_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          component_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *e.g linedetection, numberdetection, movement, acoustic, controlflow, webapp
       * </pre>
       *
       * <code>string component = 2;</code>
       */
      public Builder setComponent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        component_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *e.g linedetection, numberdetection, movement, acoustic, controlflow, webapp
       * </pre>
       *
       * <code>string component = 2;</code>
       */
      public Builder clearComponent() {
        
        component_ = getDefaultInstance().getComponent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *e.g linedetection, numberdetection, movement, acoustic, controlflow, webapp
       * </pre>
       *
       * <code>string component = 2;</code>
       */
      public Builder setComponentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        component_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Acknowledge)
    }

    // @@protoc_insertion_point(class_scope:Acknowledge)
    private static final AcknowledgeOuterClass.Acknowledge DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AcknowledgeOuterClass.Acknowledge();
    }

    public static AcknowledgeOuterClass.Acknowledge getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Acknowledge>
        PARSER = new com.google.protobuf.AbstractParser<Acknowledge>() {
      @java.lang.Override
      public Acknowledge parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Acknowledge(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Acknowledge> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Acknowledge> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AcknowledgeOuterClass.Acknowledge getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Acknowledge_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Acknowledge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021acknowledge.proto\"0\n\013Acknowledge\022\016\n\006ac" +
      "tion\030\001 \001(\t\022\021\n\tcomponent\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Acknowledge_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Acknowledge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Acknowledge_descriptor,
        new java.lang.String[] { "Action", "Component", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
