# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: direction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='direction.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64irection.proto\"\x1e\n\tDirection\x12\x11\n\tdirection\x18\x01 \x01(\tb\x06proto3')
)




_DIRECTION = _descriptor.Descriptor(
  name='Direction',
  full_name='Direction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='Direction.direction', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['Direction'] = _DIRECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Direction = _reflection.GeneratedProtocolMessageType('Direction', (_message.Message,), dict(
  DESCRIPTOR = _DIRECTION,
  __module__ = 'direction_pb2'
  # @@protoc_insertion_point(class_scope:Direction)
  ))
_sym_db.RegisterMessage(Direction)


# @@protoc_insertion_point(module_scope)
