# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='distance.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x64istance.proto\"\x1c\n\x08\x44istance\x12\x10\n\x08\x64istance\x18\x01 \x01(\x02\x62\x06proto3')
)




_DISTANCE = _descriptor.Descriptor(
  name='Distance',
  full_name='Distance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='Distance.distance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['Distance'] = _DISTANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Distance = _reflection.GeneratedProtocolMessageType('Distance', (_message.Message,), dict(
  DESCRIPTOR = _DISTANCE,
  __module__ = 'distance_pb2'
  # @@protoc_insertion_point(class_scope:Distance)
  ))
_sym_db.RegisterMessage(Distance)


# @@protoc_insertion_point(module_scope)
