# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: move_command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='move_command.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12move_command.proto\"\x1c\n\x0bMoveCommand\x12\r\n\x05speed\x18\x01 \x01(\x05\x62\x06proto3')
)




_MOVECOMMAND = _descriptor.Descriptor(
  name='MoveCommand',
  full_name='MoveCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='MoveCommand.speed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['MoveCommand'] = _MOVECOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MoveCommand = _reflection.GeneratedProtocolMessageType('MoveCommand', (_message.Message,), dict(
  DESCRIPTOR = _MOVECOMMAND,
  __module__ = 'move_command_pb2'
  # @@protoc_insertion_point(class_scope:MoveCommand)
  ))
_sym_db.RegisterMessage(MoveCommand)


# @@protoc_insertion_point(module_scope)
