# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: number_detection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='number_detection.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16number_detection.proto\"!\n\x0fNumberDetection\x12\x0e\n\x06number\x18\x01 \x01(\tb\x06proto3')
)




_NUMBERDETECTION = _descriptor.Descriptor(
  name='NumberDetection',
  full_name='NumberDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='NumberDetection.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['NumberDetection'] = _NUMBERDETECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NumberDetection = _reflection.GeneratedProtocolMessageType('NumberDetection', (_message.Message,), dict(
  DESCRIPTOR = _NUMBERDETECTION,
  __module__ = 'number_detection_pb2'
  # @@protoc_insertion_point(class_scope:NumberDetection)
  ))
_sym_db.RegisterMessage(NumberDetection)


# @@protoc_insertion_point(module_scope)
