# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: round.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='round.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bround.proto\"\x16\n\x05Round\x12\r\n\x05round\x18\x01 \x01(\x05\x62\x06proto3')
)




_ROUND = _descriptor.Descriptor(
  name='Round',
  full_name='Round',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='round', full_name='Round.round', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=37,
)

DESCRIPTOR.message_types_by_name['Round'] = _ROUND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Round = _reflection.GeneratedProtocolMessageType('Round', (_message.Message,), dict(
  DESCRIPTOR = _ROUND,
  __module__ = 'round_pb2'
  # @@protoc_insertion_point(class_scope:Round)
  ))
_sym_db.RegisterMessage(Round)


# @@protoc_insertion_point(module_scope)
