// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_command.proto

public final class SystemCommandOuterClass {
  private SystemCommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SystemCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SystemCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *e.g start, stop
     * </pre>
     *
     * <code>string command = 1;</code>
     */
    java.lang.String getCommand();
    /**
     * <pre>
     *e.g start, stop
     * </pre>
     *
     * <code>string command = 1;</code>
     */
    com.google.protobuf.ByteString
        getCommandBytes();

    /**
     * <pre>
     *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
     * </pre>
     *
     * <code>map&lt;string, bool&gt; phases = 2;</code>
     */
    int getPhasesCount();
    /**
     * <pre>
     *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
     * </pre>
     *
     * <code>map&lt;string, bool&gt; phases = 2;</code>
     */
    boolean containsPhases(
        java.lang.String key);
    /**
     * Use {@link #getPhasesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Boolean>
    getPhases();
    /**
     * <pre>
     *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
     * </pre>
     *
     * <code>map&lt;string, bool&gt; phases = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.Boolean>
    getPhasesMap();
    /**
     * <pre>
     *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
     * </pre>
     *
     * <code>map&lt;string, bool&gt; phases = 2;</code>
     */

    boolean getPhasesOrDefault(
        java.lang.String key,
        boolean defaultValue);
    /**
     * <pre>
     *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
     * </pre>
     *
     * <code>map&lt;string, bool&gt; phases = 2;</code>
     */

    boolean getPhasesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code SystemCommand}
   */
  public  static final class SystemCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SystemCommand)
      SystemCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SystemCommand.newBuilder() to construct.
    private SystemCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SystemCommand() {
      command_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SystemCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              command_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                phases_ = com.google.protobuf.MapField.newMapField(
                    PhasesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
              phases__ = input.readMessage(
                  PhasesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              phases_.getMutableMap().put(
                  phases__.getKey(), phases__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SystemCommandOuterClass.internal_static_SystemCommand_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetPhases();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SystemCommandOuterClass.internal_static_SystemCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SystemCommandOuterClass.SystemCommand.class, SystemCommandOuterClass.SystemCommand.Builder.class);
    }

    private int bitField0_;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private volatile java.lang.Object command_;
    /**
     * <pre>
     *e.g start, stop
     * </pre>
     *
     * <code>string command = 1;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *e.g start, stop
     * </pre>
     *
     * <code>string command = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHASES_FIELD_NUMBER = 2;
    private static final class PhasesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Boolean> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Boolean>newDefaultInstance(
                  SystemCommandOuterClass.internal_static_SystemCommand_PhasesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BOOL,
                  false);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Boolean> phases_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
    internalGetPhases() {
      if (phases_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PhasesDefaultEntryHolder.defaultEntry);
      }
      return phases_;
    }

    public int getPhasesCount() {
      return internalGetPhases().getMap().size();
    }
    /**
     * <pre>
     *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
     * </pre>
     *
     * <code>map&lt;string, bool&gt; phases = 2;</code>
     */

    public boolean containsPhases(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPhases().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPhasesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean> getPhases() {
      return getPhasesMap();
    }
    /**
     * <pre>
     *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
     * </pre>
     *
     * <code>map&lt;string, bool&gt; phases = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Boolean> getPhasesMap() {
      return internalGetPhases().getMap();
    }
    /**
     * <pre>
     *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
     * </pre>
     *
     * <code>map&lt;string, bool&gt; phases = 2;</code>
     */

    public boolean getPhasesOrDefault(
        java.lang.String key,
        boolean defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetPhases().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
     * </pre>
     *
     * <code>map&lt;string, bool&gt; phases = 2;</code>
     */

    public boolean getPhasesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetPhases().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCommandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, command_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetPhases(),
          PhasesDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCommandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, command_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Boolean> entry
           : internalGetPhases().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
        phases__ = PhasesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, phases__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SystemCommandOuterClass.SystemCommand)) {
        return super.equals(obj);
      }
      SystemCommandOuterClass.SystemCommand other = (SystemCommandOuterClass.SystemCommand) obj;

      boolean result = true;
      result = result && getCommand()
          .equals(other.getCommand());
      result = result && internalGetPhases().equals(
          other.internalGetPhases());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand().hashCode();
      if (!internalGetPhases().getMap().isEmpty()) {
        hash = (37 * hash) + PHASES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPhases().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SystemCommandOuterClass.SystemCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SystemCommandOuterClass.SystemCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SystemCommandOuterClass.SystemCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SystemCommandOuterClass.SystemCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SystemCommandOuterClass.SystemCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SystemCommandOuterClass.SystemCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SystemCommandOuterClass.SystemCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SystemCommandOuterClass.SystemCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SystemCommandOuterClass.SystemCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SystemCommandOuterClass.SystemCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SystemCommandOuterClass.SystemCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SystemCommandOuterClass.SystemCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SystemCommandOuterClass.SystemCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SystemCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SystemCommand)
        SystemCommandOuterClass.SystemCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SystemCommandOuterClass.internal_static_SystemCommand_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetPhases();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutablePhases();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SystemCommandOuterClass.internal_static_SystemCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SystemCommandOuterClass.SystemCommand.class, SystemCommandOuterClass.SystemCommand.Builder.class);
      }

      // Construct using SystemCommandOuterClass.SystemCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        command_ = "";

        internalGetMutablePhases().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SystemCommandOuterClass.internal_static_SystemCommand_descriptor;
      }

      @java.lang.Override
      public SystemCommandOuterClass.SystemCommand getDefaultInstanceForType() {
        return SystemCommandOuterClass.SystemCommand.getDefaultInstance();
      }

      @java.lang.Override
      public SystemCommandOuterClass.SystemCommand build() {
        SystemCommandOuterClass.SystemCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SystemCommandOuterClass.SystemCommand buildPartial() {
        SystemCommandOuterClass.SystemCommand result = new SystemCommandOuterClass.SystemCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.command_ = command_;
        result.phases_ = internalGetPhases();
        result.phases_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SystemCommandOuterClass.SystemCommand) {
          return mergeFrom((SystemCommandOuterClass.SystemCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SystemCommandOuterClass.SystemCommand other) {
        if (other == SystemCommandOuterClass.SystemCommand.getDefaultInstance()) return this;
        if (!other.getCommand().isEmpty()) {
          command_ = other.command_;
          onChanged();
        }
        internalGetMutablePhases().mergeFrom(
            other.internalGetPhases());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SystemCommandOuterClass.SystemCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SystemCommandOuterClass.SystemCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object command_ = "";
      /**
       * <pre>
       *e.g start, stop
       * </pre>
       *
       * <code>string command = 1;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *e.g start, stop
       * </pre>
       *
       * <code>string command = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *e.g start, stop
       * </pre>
       *
       * <code>string command = 1;</code>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *e.g start, stop
       * </pre>
       *
       * <code>string command = 1;</code>
       */
      public Builder clearCommand() {
        
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *e.g start, stop
       * </pre>
       *
       * <code>string command = 1;</code>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        command_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Boolean> phases_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
      internalGetPhases() {
        if (phases_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PhasesDefaultEntryHolder.defaultEntry);
        }
        return phases_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
      internalGetMutablePhases() {
        onChanged();;
        if (phases_ == null) {
          phases_ = com.google.protobuf.MapField.newMapField(
              PhasesDefaultEntryHolder.defaultEntry);
        }
        if (!phases_.isMutable()) {
          phases_ = phases_.copy();
        }
        return phases_;
      }

      public int getPhasesCount() {
        return internalGetPhases().getMap().size();
      }
      /**
       * <pre>
       *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
       * </pre>
       *
       * <code>map&lt;string, bool&gt; phases = 2;</code>
       */

      public boolean containsPhases(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetPhases().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPhasesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Boolean> getPhases() {
        return getPhasesMap();
      }
      /**
       * <pre>
       *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
       * </pre>
       *
       * <code>map&lt;string, bool&gt; phases = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Boolean> getPhasesMap() {
        return internalGetPhases().getMap();
      }
      /**
       * <pre>
       *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
       * </pre>
       *
       * <code>map&lt;string, bool&gt; phases = 2;</code>
       */

      public boolean getPhasesOrDefault(
          java.lang.String key,
          boolean defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Boolean> map =
            internalGetPhases().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
       * </pre>
       *
       * <code>map&lt;string, bool&gt; phases = 2;</code>
       */

      public boolean getPhasesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Boolean> map =
            internalGetPhases().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearPhases() {
        internalGetMutablePhases().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
       * </pre>
       *
       * <code>map&lt;string, bool&gt; phases = 2;</code>
       */

      public Builder removePhases(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutablePhases().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Boolean>
      getMutablePhases() {
        return internalGetMutablePhases().getMutableMap();
      }
      /**
       * <pre>
       *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
       * </pre>
       *
       * <code>map&lt;string, bool&gt; phases = 2;</code>
       */
      public Builder putPhases(
          java.lang.String key,
          boolean value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutablePhases().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *e.g startup, find_cube, grab_cube, round_one, round_two, find_stop, stopping, finished
       * </pre>
       *
       * <code>map&lt;string, bool&gt; phases = 2;</code>
       */

      public Builder putAllPhases(
          java.util.Map<java.lang.String, java.lang.Boolean> values) {
        internalGetMutablePhases().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SystemCommand)
    }

    // @@protoc_insertion_point(class_scope:SystemCommand)
    private static final SystemCommandOuterClass.SystemCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SystemCommandOuterClass.SystemCommand();
    }

    public static SystemCommandOuterClass.SystemCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SystemCommand>
        PARSER = new com.google.protobuf.AbstractParser<SystemCommand>() {
      @java.lang.Override
      public SystemCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SystemCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SystemCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SystemCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SystemCommandOuterClass.SystemCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SystemCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemCommand_PhasesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SystemCommand_PhasesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024system_command.proto\"{\n\rSystemCommand\022" +
      "\017\n\007command\030\001 \001(\t\022*\n\006phases\030\002 \003(\0132\032.Syste" +
      "mCommand.PhasesEntry\032-\n\013PhasesEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\010:\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SystemCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SystemCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SystemCommand_descriptor,
        new java.lang.String[] { "Command", "Phases", });
    internal_static_SystemCommand_PhasesEntry_descriptor =
      internal_static_SystemCommand_descriptor.getNestedTypes().get(0);
    internal_static_SystemCommand_PhasesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SystemCommand_PhasesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
